/**
 * boot-data.js – Bootvorgang zentral versioniert.
 * 4 Nutzungen: 1_bootvorgang (voll), 2_mac/2.1_win/2.3_linux (Boot-Screen), 2.5_iphone (abgebrochen).
 * Nach dem Einbinden: window.BOOT_DATA
 */
(function () {
  "use strict";

  window.BOOT_DATA = {
    /** 1_bootvorgang: Linux-Kernel-Boot (Linux-Nutzer erkennen sich wieder) */
    linuxLines: [
      "[    0.000000] Linux version 6.1.0-25-generic",
      "[    0.000001] Command line: BOOT_IMAGE=/vmlinuz root=UUID=xxx ro quiet splash",
      "[    0.000002] x86/fpu: Supporting XSAVE feature 0x001",
      "[    0.001234] e820: BIOS-provided physical RAM map",
      "[    0.002345] ACPI: RSDP 0x00000000000F0000 000014 (v00 ALASKA)",
      "[    0.003456] ACPI: XSDT 0x000000007FFF0030 00005C (v01 ALASKA)",
      "[    0.004567] ACPI: FACP 0x000000007FFF0100 0000F4 (v04 ALASKA)",
      "[    0.005678] ACPI: DSDT 0x000000007FFF0200 001234 (v01 ALASKA)",
      "[    0.012345] Zone ranges:",
      "[    0.012346]   DMA      [mem 0x0000000000001000-0x000000007fffffff]",
      "[    0.012347]   DMA32    [mem 0x0000000080000000-0x00000000ffffffff]",
      "[    0.012348]   Normal   [mem 0x0000000100000000-0x000000037fffffff]",
      "[    0.023456] Initramfs unpacking: Done",
      "[    0.034567] Freeing initrd memory: 123456K",
      "[    0.045678] PCI: CLS 64 bytes, default 64",
      "[    0.056789] Unpacking initramfs...",
      "[    0.067890] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x1234",
      "[    0.078901] clocksource: Switched to clocksource tsc",
      "[    0.089012] pci_bus 0000:00: root bus resource [mem 0xf0000000-0xffffffff]",
      "[    0.090123] pci 0000:00:01.0: [8086:1234] type 00 class 0x060000",
      "[    0.101234] pci 0000:00:02.0: [8086:5678] type 00 class 0x030000",
      "[    0.112345] pci 0000:00:03.0: [8086:9abc] type 00 class 0x020000",
      "[    0.123456] iommu: Default domain type: Translated",
      "[    0.134567] SCSI subsystem initialized",
      "[    0.145678] libata version 3.00 loaded.",
      "[    0.156789] usbcore: registered new interface driver usbhid",
      "[    0.167890] usbhid: USB HID core driver",
      "[    0.178901] input: AT Translated Set 2 keyboard",
      "[    0.189012] input: SynPS/2 Synaptics TouchPad",
      "[    0.190123] sd 0:0:0:0: [sda] 500107862016 512-byte logical blocks",
      "[    0.201234] sd 0:0:0:0: [sda] Write Protect is off",
      "[    0.212345]  sda1 sda2 sda3",
      "[    0.223456] EXT4-fs (sda2): mounted filesystem",
      "[    0.234567] systemd[1]: systemd 252.5 running in system mode",
      "[    0.245678] systemd[1]: Detected architecture x86-64",
      "[    0.256789] systemd[1]: Running in initial RAM disk",
      "[    0.267890] systemd[1]: Set hostname to <host>",
      "[    0.278901] systemd[1]: Created slice Slice /system/getty",
      "[    0.289012] systemd[1]: Started Dispatch Password Requests",
      "[    0.290123] systemd[1]: Reached target Local File Systems",
      "[    0.301234] systemd[1]: Reached target Swap",
      "[    0.312345] systemd[1]: Started Load/Save Random Seed",
      "[    0.323456] systemd[1]: Started udev Kernel Device Manager",
      "[    0.334567] systemd[1]: Reached target Local Encrypted Volumes",
      "[    0.345678] systemd[1]: Reached target Paths",
      "[    0.356789] systemd[1]: Reached target Basic System",
      "[    0.367890] systemd[1]: Started Journal Service",
      "[    0.378901] systemd[1]: Started Create Static Device Nodes",
      "[    0.389012] systemd[1]: Reached target System Initialization",
      "[    0.390123] systemd[1]: Started Load Kernel Modules",
      "[    0.401234] systemd[1]: Started Apply Kernel Variables",
      "[    0.412345] systemd[1]: Reached target Local File Systems (Pre)",
      "[    0.423456] systemd[1]: Started udev Coldplug all Devices",
      "[    0.434567] systemd[1]: Started Load/Save Screen Backlight",
      "[    0.445678] systemd[1]: Reached target System Time Synchronized",
      "[    0.456789] systemd[1]: Reached target Network (Pre)",
      "[    0.467890] systemd[1]: Started Network Manager",
      "[    0.478901] systemd[1]: Reached target Network",
      "[    0.489012] systemd[1]: Started OpenSSH server daemon",
      "[    0.490123] systemd[1]: Reached target Multi-User System",
      "[    0.501234] systemd[1]: Reached target Graphical Interface",
      "[    0.512345] systemd[1]: Startup finished in 0.512s",
      "[    0.523456] audit: type=1400 audit(1234567890.123:1): apparmor=\"STATUS\"",
      "[    0.534567] audit: type=1400 audit(1234567890.234:2): apparmor=\"STATUS\"",
      "[    0.545678] Bluetooth: Core ver 2.22",
      "[    0.556789] NET: Registered PF_BLUETOOTH protocol family",
      "[    0.567890] Bluetooth: HCI device and connection manager initialized",
      "[    0.578901] Bluetooth: HCI socket layer initialized",
      "[    0.589012] Bluetooth: L2CAP socket layer initialized",
      "[    0.590123] Bluetooth: SCO socket layer initialized",
      "[    0.601234] cfg80211: Loading compiled-in X.509 certificates",
      "[    0.612345] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'",
      "[    0.623456] platform regulatory.0: Direct firmware load for regulatory.db",
      "[    0.634567] iwlwifi 0000:03:00.0: enabling device (0000 -> 0002)",
      "[    0.645678] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-ty-a0-gf-a0-72.ucode",
      "[    0.656789] iwlwifi 0000:03:00.0: loaded firmware version 72.601fbb1e.0",
      "[    0.667890] iwlwifi 0000:03:00.0: Detected Intel(R) Wi-Fi 6 AX201 160MHz",
      "[    0.678901] iwlwifi 0000:03:00.0: base HW address: aa:bb:cc:dd:ee:ff",
      "[    0.689012] iwlwifi 0000:03:00.0 wlan0: renamed from wlan0",
      "[    0.690123] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready",
      "[    0.701234] wlp3s0: authenticate with aa:bb:cc:dd:ee:ff",
      "[    0.712345] wlp3s0: send auth to aa:bb:cc:dd:ee:ff (try 1/3)",
      "[    0.723456] wlp3s0: authenticated",
      "[    0.734567] wlp3s0: associate with aa:bb:cc:dd:ee:ff (try 1/3)",
      "[    0.745678] wlp3s0: RX AssocResp from aa:bb:cc:dd:ee:ff (capab=0x1411)",
      "[    0.756789] wlp3s0: associated",
      "[    0.767890] IPv6: ADDRCONF(NETDEV_CHANGE): wlp3s0: link becomes ready",
      "[    0.778901] audit: type=1130 audit(1234567890.345:3): pid=1 uid=0 auid=4294967295",
      "[    0.789012] random: crng init done",
      "[    0.790123] random: 7 urandom warning(s) missed due to ratelimiting",
      "[    0.801234] PM: hibernation: Image not found or resuming",
      "[    0.812345] Freeing unused kernel image (initmem) memory: 1234K",
      "[    0.823456] Write protecting the kernel read-only data: 20480k",
      "[    0.834567] Freeing unused kernel image (text/rodata gap) memory: 2048K",
      "[    0.845678] Freeing unused kernel image (rodata/data gap) memory: 512K",
      "[    0.856789] x86/mm: Checked W+X mappings: passed, no W+X pages found",
      "[    0.867890] Run /init as init process",
      "[    0.878901] Run /sbin/init as init process",
      "[    0.889012] Run /lib/systemd/systemd as init process",
      "[    0.890123] systemd[1]: Inserted module 'autofs4'",
      "[    0.901234] systemd[1]: Inserted module 'unix'",
      "[    0.912345] systemd[1]: Mounting cgroup2...",
      "[    0.923456] systemd[1]: Mounted cgroup2.",
      "[    0.934567] systemd[1]: Mounting sysfs...",
      "[    0.945678] systemd[1]: Mounted sysfs.",
      "[    0.956789] systemd[1]: Mounting proc...",
      "[    0.967890] systemd[1]: Mounted proc.",
      "[    0.978901] systemd[1]: Mounting dev...",
      "[    0.989012] systemd[1]: Mounted dev.",
      "[    0.990123] systemd[1]: Mounting run...",
      "[    1.001234] systemd[1]: Mounted run.",
      "[    1.012345] systemd[1]: Reached target Initrd Root File System",
      "[    1.023456] systemd[1]: Reached target Initrd File Systems",
      "[    1.034567] systemd[1]: Reached target Initrd Default Target",
      "[    1.045678] systemd[1]: Starting initrd.target...",
      "[    1.056789] systemd[1]: Reached target initrd.target.",
      "[    1.067890] systemd[1]: Detected virtualization none.",
      "[    1.078901] systemd[1]: Detected architecture x86-64.",
      "[    1.089012] systemd[1]: Hostname set to <host>.",
      "[    1.090123] systemd[1]: Queued start job for default target Graphical Interface.",
      "[    1.101234] systemd[1]: Created slice system-getty.slice.",
      "[    1.112345] systemd[1]: Created slice system-modprobe.slice.",
      "[    1.123456] systemd[1]: Created slice user.slice.",
      "[    1.134567] systemd[1]: Started Dispatch Password Requests to Console Directory.",
      "[    1.145678] systemd[1]: Started Forward Password Requests to Wall Directory.",
      "[    1.156789] systemd[1]: Set up automount Arbitrary Executable File Formats.",
      "[    1.167890] systemd[1]: Reached target Local Encrypted Volumes.",
      "[    1.178901] systemd[1]: Reached target Paths.",
      "[    1.189012] systemd[1]: Reached target Slices.",
      "[    1.190123] systemd[1]: Reached target Swap.",
      "[    1.201234] systemd[1]: Reached target Local File Systems (Pre).",
      "[    1.212345] systemd[1]: Reached target Local File Systems.",
      "[    1.223456] systemd[1]: Reached target Remote File Systems.",
      "[    1.234567] systemd[1]: Reached target System Time Set.",
      "[    1.245678] systemd[1]: Reached target System Time Synchronized.",
      "[    1.256789] systemd[1]: Reached target Timers.",
      "[    1.267890] systemd[1]: Reached target Socket Units.",
      "[    1.278901] systemd[1]: Reached target Basic System.",
      "[    1.289012] systemd[1]: Reached target System Initialization.",
      "[    1.290123] systemd[1]: Reached target Initialization Complete.",
      "[    1.301234] systemd[1]: Reached target Multi-User System.",
      "[    1.312345] systemd[1]: Reached target Graphical Interface.",
      "[    1.323456] systemd[1]: Startup finished in 1.323s (kernel) + 2.456s (initrd) + 3.789s (userspace) = 7.568s total."
    ],

    /** 1_bootvorgang: Linux LILO/Debian-Boot mit Delays (wie winBootSequence) – Pause bei „Loading Linux…“, dann Rauschen */
    linuxBootSequence: [
      { text: "LILO 21.7.5 Booting...", delay: 375 },
      { text: "Loading Linux......................................................", delay: 900 },
      { text: "BIOS-provided physical RAM map:", delay: 38 },
      { text: " BIOS-e820: 0000000000000000 - 000000000009f000 (usable)", delay: 8 },
      { text: " BIOS-e820: 000000000009f000 - 00000000000a0000 (reserved)", delay: 8 },
      { text: " BIOS-e820: 0000000000100000 - 0000000007ff0000 (usable)", delay: 8 },
      { text: "Console: colour VGA+ 80x25", delay: 75 },
      { text: "Calibrating delay loop... 266.24 BogoMIPS", delay: 450 },
      { text: "PCI: Probing PCI hardware", delay: 150 },
      { text: "PCI: Using configuration type 1", delay: 8 },
      { text: "PCI: Found 00:00.0 [8086/7190] Host bridge", delay: 4 },
      { text: "PCI: Found 00:01.0 [8086/7191] PCI-to-PCI bridge", delay: 4 },
      { text: "PCI: Found 00:07.0 [8086/7110] ISA bridge", delay: 4 },
      { text: "PCI: Found 00:07.1 [8086/7111] IDE interface", delay: 4 },
      { text: "PCI: Found 00:07.2 [8086/7112] USB Controller", delay: 4 },
      { text: "PCI: Found 00:07.3 [8086/7113] Bridge", delay: 4 },
      { text: "PCI: Found 00:0d.0 [10ec/8139] Ethernet controller", delay: 4 },
      { text: "ide0: BM-DMA at 0xff00-0xff07, BIOS settings: hda:DMA, hdb:pio", delay: 15 },
      { text: "hda: ST31276A, 1220MB w/128kB Cache, CHS=2479/16/63", delay: 8 },
      { text: "hdb: TOSHIBA CD-ROM XM-5702B, ATAPI CDROM drive", delay: 8 },
      { text: "Partition check:", delay: 38 },
      { text: " hda: [PTBL] [2479/16/63] hda1 hda2 hda3 < hda5 hda6 hda7 hda8 >", delay: 8 },
      { text: "EXT2-fs warning: mounting unchecked fs, running e2fsck is recommended", delay: 75 },
      { text: "VFS: Mounted root (ext2 filesystem) readonly.", delay: 150 },
      { text: "usb.c: registered new driver hub", delay: 4 },
      { text: "usb-uhci.c: $Revision: 1.251 $ time 12:45:01", delay: 4 },
      { text: "usb-uhci.c: High Link [0xec00] irq 11", delay: 4 },
      { text: "hub.c: USB hub found", delay: 4 },
      { text: "hub.c: 2 ports detected", delay: 4 },
      { text: "usb.c: registered new driver hid", delay: 4 },
      { text: "hid-core.c: v1.81 Andreas Gal v1.810521", delay: 4 },
      { text: "usb.c: registered new driver audio", delay: 4 },
      { text: "audio.c: v1.0.0 Johannes Erdfelt", delay: 4 },
      { text: "INIT: version 2.76 booting", delay: 225 },
      { text: "Setting hostname: debian-station [OK]", delay: 15 },
      { text: "Mounting local filesystems... [OK]", delay: 15 },
      { text: "Enabling packet filtering: ufw [OK]", delay: 8 },
      { text: "Starting system log daemon: syslogd [OK]", delay: 8 },
      { text: "Starting kernel log daemon: klogd [OK]", delay: 8 },
      { text: "[FAILED] kernel-module: sound-blaster", delay: 38, error: true },
      { text: "Initializing random number generator... [OK]", delay: 75 },
      { text: "Cleaning /tmp /var/run /var/lock... [OK]", delay: 8 },
      { text: "Configuring network interfaces: lo [OK]", delay: 8 },
      { text: "Configuring network interfaces: eth0 [OK]", delay: 150 },
      { text: "Starting portmapper: [OK]", delay: 8 },
      { text: "Starting NFS services: statd [OK]", delay: 8 },
      { text: "Starting sendmail: [OK]", delay: 38 },
      { text: "Starting apache-httpd: [OK]", delay: 30 },
      { text: "Starting mysql-server: [OK]", delay: 75 },
      { text: "Starting postgresql-server: [OK]", delay: 75 },
      { text: "Starting sshd: [OK]", delay: 38 },
      { text: "Starting exim4: [OK]", delay: 15 },
      { text: "Starting inetd: [OK]", delay: 8 },
      { text: "Starting lpd: [OK]", delay: 8 },
      { text: "Starting cupsd: [OK]", delay: 23 },
      { text: "Starting samba: [OK]", delay: 38 },
      { text: "Starting winbind: [OK]", delay: 15 },
      { text: "Starting nscd: [OK]", delay: 8 },
      { text: "Starting xfs (X Font Server): [OK]", delay: 8 },
      { text: "Starting gpm (mouse console): [OK]", delay: 15 },
      { text: "[FAILED] pcmcia: cardmgr (optional)", delay: 23, error: true },
      { text: "Starting atd: [OK]", delay: 8 },
      { text: "Starting crond: [OK]", delay: 8 },
      { text: "Starting anacron: [OK]", delay: 4 },
      { text: "Starting atd: [OK]", delay: 4 },
      { text: "Starting batch: [OK]", delay: 4 },
      { text: "Starting systemd-timesyncd: [OK]", delay: 4 },
      { text: "Starting systemd-journal-remote: [OK]", delay: 4 },
      { text: "Starting systemd-journal-upload: [OK]", delay: 4 },
      { text: "Starting systemd-journal-gatewayd: [OK]", delay: 4 },
      { text: "Starting systemd-journal-devlog: [OK]", delay: 4 },
      { text: "Starting systemd-bootchart: [OK]", delay: 4 },
      { text: "Starting systemd-coredump: [OK]", delay: 4 },
      { text: "Starting systemd-coredump.socket: [OK]", delay: 4 },
      { text: "Starting systemd-networkd: [OK]", delay: 4 },
      { text: "Starting systemd-networkd-wait-online: [OK]", delay: 4 },
      { text: "Starting systemd-nspawn: [OK]", delay: 4 },
      { text: "Starting systemd-user-sessions: [OK]", delay: 4 },
      { text: "Starting user@0.service: [OK]", delay: 4 },
      { text: "Starting user@1000.service: [OK]", delay: 4 },
      { text: "Starting getty@tty1: [OK]", delay: 4 },
      { text: "Starting getty@tty2: [OK]", delay: 4 },
      { text: "Starting getty@tty3: [OK]", delay: 4 },
      { text: "Starting getty@tty4: [OK]", delay: 4 },
      { text: "Starting getty@tty5: [OK]", delay: 4 },
      { text: "Starting getty@tty6: [OK]", delay: 4 },
      { text: "Starting serial-getty@ttyS0: [OK]", delay: 4 },
      { text: "Starting console-getty: [OK]", delay: 4 },
      { text: "Starting ssh.socket: [OK]", delay: 4 },
      { text: "Starting cups.socket: [OK]", delay: 4 },
      { text: "Starting avahi-daemon.socket: [OK]", delay: 4 },
      { text: "Starting dbus.socket: [OK]", delay: 4 },
      { text: "Starting docker.socket: [OK]", delay: 4 },
      { text: "Starting rpcbind.socket: [OK]", delay: 4 },
      { text: "Starting uuidd.socket: [OK]", delay: 4 },
      { text: "Starting lvm2-lvmetad.socket: [OK]", delay: 4 },
      { text: "Starting lvm2-lvmpolld.socket: [OK]", delay: 4 },
      { text: "Starting iscsi.socket: [OK]", delay: 4 },
      { text: "Starting iscsid.socket: [OK]", delay: 4 },
      { text: "Starting iscsiuio.socket: [OK]", delay: 4 },
      { text: "Starting gssproxy.socket: [OK]", delay: 4 },
      { text: "Starting pcscd.socket: [OK]", delay: 4 },
      { text: "Starting snapd.socket: [OK]", delay: 4 },
      { text: "Starting snapd.core-fixup: [OK]", delay: 4 },
      { text: "Starting snapd.autoimport: [OK]", delay: 4 },
      { text: "Starting snapd.refresh: [OK]", delay: 4 },
      { text: "Starting snapd.snap-repair: [OK]", delay: 4 },
      { text: "Starting snapd.seeded: [OK]", delay: 4 },
      { text: "Starting lxd-containers: [OK]", delay: 4 },
      { text: "Starting lxd.socket: [OK]", delay: 4 },
      { text: "Starting lxd: [OK]", delay: 4 },
      { text: "Starting lxcfs: [OK]", delay: 4 },
      { text: "Starting lxc-net: [OK]", delay: 4 },
      { text: "Starting lxc: [OK]", delay: 4 },
      { text: "Starting lxc-monitord: [OK]", delay: 4 },
      { text: "Starting lxcfs: [OK]", delay: 4 },
      { text: "Starting lxd-bridge: [OK]", delay: 4 },
      { text: "Starting lxd-agent: [OK]", delay: 4 },
      { text: "Starting lxd-agent-9p: [OK]", delay: 4 },
      { text: "Starting qemu-guest-agent: [OK]", delay: 4 },
      { text: "Starting spice-vdagent: [OK]", delay: 4 },
      { text: "Starting open-vm-tools: [OK]", delay: 4 },
      { text: "Starting vmtoolsd: [OK]", delay: 4 },
      { text: "Starting vgauth: [OK]", delay: 4 },
      { text: "Starting vmware-tools: [OK]", delay: 4 },
      { text: "Starting vmware-tools-thinprint: [OK]", delay: 4 },
      { text: "Starting virtualbox-guest-utils: [OK]", delay: 4 },
      { text: "Starting virtualbox-guest-x11: [OK]", delay: 4 },
      { text: "Starting vboxadd: [OK]", delay: 4 },
      { text: "Starting vboxadd-service: [OK]", delay: 4 },
      { text: "Starting vboxadd-x11: [OK]", delay: 4 },
      { text: "Loading kernel module: nfs [OK]", delay: 4 },
      { text: "Loading kernel module: nfsd [OK]", delay: 4 },
      { text: "Loading kernel module: lockd [OK]", delay: 4 },
      { text: "Loading kernel module: sunrpc [OK]", delay: 4 },
      { text: "Loading kernel module: ext2 [OK]", delay: 4 },
      { text: "Loading kernel module: ext3 [OK]", delay: 4 },
      { text: "Loading kernel module: reiserfs [OK]", delay: 4 },
      { text: "Loading kernel module: jbd [OK]", delay: 4 },
      { text: "Loading kernel module: dm-mod [OK]", delay: 4 },
      { text: "Loading kernel module: loop [OK]", delay: 4 },
      { text: "Loading kernel module: crc32 [OK]", delay: 4 },
      { text: "Loading kernel module: mbcache [OK]", delay: 4 },
      { text: "Loading kernel module: sd_mod [OK]", delay: 4 },
      { text: "Loading kernel module: sr_mod [OK]", delay: 4 },
      { text: "Loading kernel module: sg [OK]", delay: 4 },
      { text: "Loading kernel module: usb-storage [OK]", delay: 4 },
      { text: "Loading kernel module: uhci-hcd [OK]", delay: 4 },
      { text: "Loading kernel module: ehci-hcd [OK]", delay: 4 },
      { text: "Loading kernel module: usbcore [OK]", delay: 4 },
      { text: "Loading kernel module: 8139too [OK]", delay: 4 },
      { text: "Loading kernel module: e100 [OK]", delay: 4 },
      { text: "Loading kernel module: ppdev [OK]", delay: 4 },
      { text: "Loading kernel module: parport_pc [OK]", delay: 4 },
      { text: "Loading kernel module: parport [OK]", delay: 4 },
      { text: "Starting dbus: [OK]", delay: 8 },
      { text: "Starting acpid: [OK]", delay: 8 },
      { text: "Starting hald: [OK]", delay: 8 },
      { text: "Starting rsyslog: [OK]", delay: 8 },
      { text: "Starting bootlogd: [OK]", delay: 8 },
      { text: "Starting console-setup: [OK]", delay: 8 },
      { text: "Starting mtab.sh: [OK]", delay: 4 },
      { text: "Starting checkroot: [OK]", delay: 4 },
      { text: "Starting mountall: [OK]", delay: 4 },
      { text: "Starting urandom: [OK]", delay: 4 },
      { text: "Starting hwclock: [OK]", delay: 4 },
      { text: "Starting networking: [OK]", delay: 8 },
      { text: "Starting ntp: [OK]", delay: 15 },
      { text: "Starting ssh: [OK]", delay: 8 },
      { text: "Starting cron: [OK]", delay: 4 },
      { text: "Starting anacron: [OK]", delay: 4 },
      { text: "Starting at: [OK]", delay: 4 },
      { text: "Starting sysklogd: [OK]", delay: 4 },
      { text: "Starting klogd: [OK]", delay: 4 },
      { text: "Starting portmap: [OK]", delay: 4 },
      { text: "Starting nfs-common: [OK]", delay: 4 },
      { text: "Starting rpcbind: [OK]", delay: 4 },
      { text: "Starting rpc.nfsd: [OK]", delay: 4 },
      { text: "Starting rpc.mountd: [OK]", delay: 4 },
      { text: "Starting rpc.statd: [OK]", delay: 4 },
      { text: "Starting rpc.idmapd: [OK]", delay: 4 },
      { text: "Starting quota: [OK]", delay: 4 },
      { text: "Starting fetchmail: [OK]", delay: 4 },
      { text: "Starting procmail: [OK]", delay: 4 },
      { text: "Starting spamassassin: [OK]", delay: 4 },
      { text: "Starting clamav-daemon: [OK]", delay: 4 },
      { text: "Starting postfix: [OK]", delay: 8 },
      { text: "Starting dovecot: [OK]", delay: 4 },
      { text: "Starting cyrus-imapd: [OK]", delay: 4 },
      { text: "Starting slapd: [OK]", delay: 4 },
      { text: "Starting bind9: [OK]", delay: 4 },
      { text: "Starting named: [OK]", delay: 4 },
      { text: "Starting dhcp3-server: [OK]", delay: 4 },
      { text: "Starting radvd: [OK]", delay: 4 },
      { text: "Starting openvpn: [OK]", delay: 4 },
      { text: "Starting iptables: [OK]", delay: 4 },
      { text: "Starting ip6tables: [OK]", delay: 4 },
      { text: "Starting fail2ban: [OK]", delay: 4 },
      { text: "Starting snmpd: [OK]", delay: 4 },
      { text: "Starting munin-node: [OK]", delay: 4 },
      { text: "Starting nagios: [OK]", delay: 4 },
      { text: "Starting collectd: [OK]", delay: 4 },
      { text: "Starting ganglia-monitor: [OK]", delay: 4 },
      { text: "Starting tomcat6: [OK]", delay: 4 },
      { text: "Starting jetty: [OK]", delay: 4 },
      { text: "Starting glassfish: [OK]", delay: 4 },
      { text: "Starting jboss: [OK]", delay: 4 },
      { text: "Starting redis-server: [OK]", delay: 4 },
      { text: "Starting memcached: [OK]", delay: 4 },
      { text: "Starting rabbitmq-server: [OK]", delay: 4 },
      { text: "Starting beanstalkd: [OK]", delay: 4 },
      { text: "Starting elasticsearch: [OK]", delay: 4 },
      { text: "Starting mongodb: [OK]", delay: 4 },
      { text: "Starting couchdb: [OK]", delay: 4 },
      { text: "Starting influxdb: [OK]", delay: 4 },
      { text: "Starting grafana-server: [OK]", delay: 4 },
      { text: "Starting prometheus: [OK]", delay: 4 },
      { text: "Starting node: [OK]", delay: 4 },
      { text: "Starting php7.4-fpm: [OK]", delay: 4 },
      { text: "Starting php-fpm: [OK]", delay: 4 },
      { text: "Starting uwsgi: [OK]", delay: 4 },
      { text: "Starting gunicorn: [OK]", delay: 4 },
      { text: "Starting lighttpd: [OK]", delay: 4 },
      { text: "Starting nginx: [OK]", delay: 4 },
      { text: "Starting squid: [OK]", delay: 4 },
      { text: "Starting varnish: [OK]", delay: 4 },
      { text: "Starting haproxy: [OK]", delay: 4 },
      { text: "Starting keepalived: [OK]", delay: 4 },
      { text: "Starting corosync: [OK]", delay: 4 },
      { text: "Starting pacemaker: [OK]", delay: 4 },
      { text: "Starting drbd: [OK]", delay: 4 },
      { text: "Starting ocfs2: [OK]", delay: 4 },
      { text: "Starting cman: [OK]", delay: 4 },
      { text: "Starting clvmd: [OK]", delay: 4 },
      { text: "Starting gfs2: [OK]", delay: 4 },
      { text: "Starting lvm2: [OK]", delay: 4 },
      { text: "Starting mdadm: [OK]", delay: 4 },
      { text: "Starting multipathd: [OK]", delay: 4 },
      { text: "Starting iscsid: [OK]", delay: 4 },
      { text: "Starting open-iscsi: [OK]", delay: 4 },
      { text: "Starting tgt: [OK]", delay: 4 },
      { text: "Starting libvirt-bin: [OK]", delay: 4 },
      { text: "Starting qemu-kvm: [OK]", delay: 4 },
      { text: "Starting libvirt-guests: [OK]", delay: 4 },
      { text: "Starting virtlogd: [OK]", delay: 4 },
      { text: "Starting virtlockd: [OK]", delay: 4 },
      { text: "Starting cgconfig: [OK]", delay: 4 },
      { text: "Starting cgred: [OK]", delay: 4 },
      { text: "Starting bluetooth: [OK]", delay: 4 },
      { text: "Starting avahi-daemon: [OK]", delay: 4 },
      { text: "Starting wpa_supplicant: [OK]", delay: 4 },
      { text: "Starting network-manager: [OK]", delay: 4 },
      { text: "Starting ModemManager: [OK]", delay: 4 },
      { text: "Starting upower: [OK]", delay: 4 },
      { text: "Starting udisks-daemon: [OK]", delay: 4 },
      { text: "Starting colord: [OK]", delay: 4 },
      { text: "Starting accounts-daemon: [OK]", delay: 4 },
      { text: "Starting polkitd: [OK]", delay: 4 },
      { text: "Starting rtkit-daemon: [OK]", delay: 4 },
      { text: "Starting pulseaudio: [OK]", delay: 4 },
      { text: "Starting alsa-restore: [OK]", delay: 4 },
      { text: "Starting saned: [OK]", delay: 4 },
      { text: "Starting cups-browsed: [OK]", delay: 4 },
      { text: "Starting apparmor: [OK]", delay: 4 },
      { text: "Starting irqbalance: [OK]", delay: 4 },
      { text: "Starting lm-sensors: [OK]", delay: 4 },
      { text: "Starting smartd: [OK]", delay: 4 },
      { text: "Starting mdmonitor: [OK]", delay: 4 },
      { text: "Starting watchdog: [OK]", delay: 4 },
      { text: "Starting systemd-logind: [OK]", delay: 4 },
      { text: "Starting systemd-udevd: [OK]", delay: 4 },
      { text: "Starting systemd-journald: [OK]", delay: 4 },
      { text: "Starting systemd-timesyncd: [OK]", delay: 4 },
      { text: "Starting systemd-resolved: [OK]", delay: 4 },
      { text: "Starting systemd-networkd: [OK]", delay: 4 },
      { text: "Starting unattended-upgrades: [OK]", delay: 4 },
      { text: "Starting apt-daily: [OK]", delay: 4 },
      { text: "Starting apt-daily-upgrade: [OK]", delay: 4 },
      { text: "Starting dpkg-db-backup: [OK]", delay: 4 },
      { text: "Starting logrotate: [OK]", delay: 4 },
      { text: "Starting man-db: [OK]", delay: 4 },
      { text: "Starting mlocate: [OK]", delay: 4 },
      { text: "Starting x11-common: [OK]", delay: 4 },
      { text: "Starting xorg: [OK]", delay: 4 },
      { text: "Starting postgresql-9.4: [OK]", delay: 4 },
      { text: "Starting postgresql-10: [OK]", delay: 4 },
      { text: "Starting postgresql-11: [OK]", delay: 4 },
      { text: "Starting postgresql-12: [OK]", delay: 4 },
      { text: "Starting mysql: [OK]", delay: 4 },
      { text: "Starting mariadb: [OK]", delay: 4 },
      { text: "Starting percona-server: [OK]", delay: 4 },
      { text: "Starting mysqld: [OK]", delay: 4 },
      { text: "Starting slapd: [OK]", delay: 4 },
      { text: "Starting 389-ds: [OK]", delay: 4 },
      { text: "Starting openldap: [OK]", delay: 4 },
      { text: "Starting sssd: [OK]", delay: 4 },
      { text: "Starting winbind: [OK]", delay: 4 },
      { text: "Starting smbd: [OK]", delay: 4 },
      { text: "Starting nmbd: [OK]", delay: 4 },
      { text: "Starting krb5-kdc: [OK]", delay: 4 },
      { text: "Starting krb5-admin-server: [OK]", delay: 4 },
      { text: "Starting nfs-kernel-server: [OK]", delay: 4 },
      { text: "Starting nfs-common: [OK]", delay: 4 },
      { text: "Starting rpcbind: [OK]", delay: 4 },
      { text: "Starting isc-dhcp-server: [OK]", delay: 4 },
      { text: "Starting isc-dhcp-server6: [OK]", delay: 4 },
      { text: "Starting dnsmasq: [OK]", delay: 4 },
      { text: "Starting unbound: [OK]", delay: 4 },
      { text: "Starting pdns: [OK]", delay: 4 },
      { text: "Starting pdns-recursor: [OK]", delay: 4 },
      { text: "Starting powerdns: [OK]", delay: 4 },
      { text: "Starting knot: [OK]", delay: 4 },
      { text: "Starting nsd: [OK]", delay: 4 },
      { text: "Starting unbound-resolvconf: [OK]", delay: 4 },
      { text: "Starting systemd-resolved: [OK]", delay: 4 },
      { text: "Starting apache2: [OK]", delay: 4 },
      { text: "Starting nginx: [OK]", delay: 4 },
      { text: "Starting lighttpd: [OK]", delay: 4 },
      { text: "Starting cherokee: [OK]", delay: 4 },
      { text: "Starting thin: [OK]", delay: 4 },
      { text: "Starting puma: [OK]", delay: 4 },
      { text: "Starting unicorn: [OK]", delay: 4 },
      { text: "Starting passenger: [OK]", delay: 4 },
      { text: "Starting varnish: [OK]", delay: 4 },
      { text: "Starting varnishncsa: [OK]", delay: 4 },
      { text: "Starting squid: [OK]", delay: 4 },
      { text: "Starting squid3: [OK]", delay: 4 },
      { text: "Starting haproxy: [OK]", delay: 4 },
      { text: "Starting stud: [OK]", delay: 4 },
      { text: "Starting stunnel4: [OK]", delay: 4 },
      { text: "Starting openvpn: [OK]", delay: 4 },
      { text: "Starting openvpn-server: [OK]", delay: 4 },
      { text: "Starting openvpn-client: [OK]", delay: 4 },
      { text: "Starting strongswan: [OK]", delay: 4 },
      { text: "Starting ipsec: [OK]", delay: 4 },
      { text: "Starting xl2tpd: [OK]", delay: 4 },
      { text: "Starting pptpd: [OK]", delay: 4 },
      { text: "Starting wireguard: [OK]", delay: 4 },
      { text: "Starting tor: [OK]", delay: 4 },
      { text: "Starting privoxy: [OK]", delay: 4 },
      { text: "Starting polipo: [OK]", delay: 4 },
      { text: "Starting tinyproxy: [OK]", delay: 4 },
      { text: "Starting shinken: [OK]", delay: 4 },
      { text: "Starting icinga2: [OK]", delay: 4 },
      { text: "Starting zabbix-agent: [OK]", delay: 4 },
      { text: "Starting zabbix-server: [OK]", delay: 4 },
      { text: "Starting zabbix-proxy: [OK]", delay: 4 },
      { text: "Starting telegraf: [OK]", delay: 4 },
      { text: "Starting influxdb: [OK]", delay: 4 },
      { text: "Starting kapacitor: [OK]", delay: 4 },
      { text: "Starting chronograf: [OK]", delay: 4 },
      { text: "Starting grafana-server: [OK]", delay: 4 },
      { text: "Starting prometheus: [OK]", delay: 4 },
      { text: "Starting alertmanager: [OK]", delay: 4 },
      { text: "Starting node_exporter: [OK]", delay: 4 },
      { text: "Starting cadvisor: [OK]", delay: 4 },
      { text: "Starting docker: [OK]", delay: 4 },
      { text: "Starting containerd: [OK]", delay: 4 },
      { text: "Starting runc: [OK]", delay: 4 },
      { text: "Starting dockerd: [OK]", delay: 4 },
      { text: "Starting docker.socket: [OK]", delay: 4 },
      { text: "Starting kubelet: [OK]", delay: 4 },
      { text: "Starting kube-proxy: [OK]", delay: 4 },
      { text: "Starting etcd: [OK]", delay: 4 },
      { text: "Starting flanneld: [OK]", delay: 4 },
      { text: "Starting consul: [OK]", delay: 4 },
      { text: "Starting nomad: [OK]", delay: 4 },
      { text: "Starting vault: [OK]", delay: 4 },
      { text: "Starting serf: [OK]", delay: 4 },
      { text: "Starting mesos-master: [OK]", delay: 4 },
      { text: "Starting mesos-slave: [OK]", delay: 4 },
      { text: "Starting marathon: [OK]", delay: 4 },
      { text: "Starting chronos: [OK]", delay: 4 },
      { text: "Starting spark-master: [OK]", delay: 4 },
      { text: "Starting spark-worker: [OK]", delay: 4 },
      { text: "Starting hadoop-hdfs-namenode: [OK]", delay: 4 },
      { text: "Starting hadoop-hdfs-datanode: [OK]", delay: 4 },
      { text: "Starting hadoop-yarn-resourcemanager: [OK]", delay: 4 },
      { text: "Starting hadoop-yarn-nodemanager: [OK]", delay: 4 },
      { text: "Starting hbase-master: [OK]", delay: 4 },
      { text: "Starting hbase-regionserver: [OK]", delay: 4 },
      { text: "Starting zookeeper: [OK]", delay: 4 },
      { text: "Starting kafka: [OK]", delay: 4 },
      { text: "Starting cassandra: [OK]", delay: 4 },
      { text: "Starting riak: [OK]", delay: 4 },
      { text: "Starting couchbase-server: [OK]", delay: 4 },
      { text: "Starting neo4j: [OK]", delay: 4 },
      { text: "Starting orientdb: [OK]", delay: 4 },
      { text: "Starting arangodb3: [OK]", delay: 4 },
      { text: "Starting elasticsearch: [OK]", delay: 4 },
      { text: "Starting logstash: [OK]", delay: 4 },
      { text: "Starting kibana: [OK]", delay: 4 },
      { text: "Starting filebeat: [OK]", delay: 4 },
      { text: "Starting metricbeat: [OK]", delay: 4 },
      { text: "Starting packetbeat: [OK]", delay: 4 },
      { text: "Starting auditd: [OK]", delay: 4 },
      { text: "Starting rsyslog: [OK]", delay: 4 },
      { text: "Starting syslog-ng: [OK]", delay: 4 },
      { text: "Starting fluentd: [OK]", delay: 4 },
      { text: "Starting vector: [OK]", delay: 4 },
      { text: "Starting display-manager: [OK]", delay: 8 },
      { text: "Starting gdm3: [OK]", delay: 4 },
      { text: "Starting lightdm: [OK]", delay: 4 },
      { text: "Starting sddm: [OK]", delay: 4 },
      { text: "Starting wdm: [OK]", delay: 4 },
      { text: "Starting xdm: [OK]", delay: 4 },
      { text: "Starting kdm: [OK]", delay: 4 },
      { text: "kernel: [    0.001234] scsi0 : BusLogic BT-958", delay: 4 },
      { text: "kernel: [    0.002345] scsi1 : Adaptec AHA-2940", delay: 4 },
      { text: "kernel: [    0.003456] scsi 0:0:0:0 Direct-Access SEAGATE ST31276A", delay: 4 },
      { text: "kernel: [    0.004567] scsi 0:0:1:0 CD-ROM TOSHIBA CD-ROM XM-5702B", delay: 4 },
      { text: "kernel: [    0.005678] sd 0:0:0:0: [sda] 238475 512-byte blocks", delay: 4 },
      { text: "kernel: [    0.006789] sd 0:0:0:0: [sda] Write Protect is off", delay: 4 },
      { text: "kernel: [    0.007890] sr0: scsi3-mmc drive: 24x/24x", delay: 4 },
      { text: "kernel: [    0.008901] eth0: RealTek RTL8139 at 0xe400, 00:0a:e4:12:34:56", delay: 4 },
      { text: "kernel: [    0.009012] input: AT Translated Set 2 keyboard", delay: 4 },
      { text: "kernel: [    0.010123] input: ImPS/2 Generic Wheel Mouse", delay: 4 },
      { text: "kernel: [    0.011234] serio: PS/2 controller found", delay: 4 },
      { text: "kernel: [    0.012345] EISA: Probing bus 0 at Base 0x00000000", delay: 4 },
      { text: "kernel: [    0.013456] PCI: Enabling device 00:07.2 (0000 -> 0003)", delay: 4 },
      { text: "kernel: [    0.014567] ACPI: PCI interrupt for device 00:07.2", delay: 4 },
      { text: "kernel: [    0.015678] usb 1-1: new full speed USB device", delay: 4 },
      { text: "kernel: [    0.016789] usb 2-1: new high speed USB device", delay: 4 },
      { text: "kernel: [    0.017890] usbcore: registered new interface driver usbhid", delay: 4 },
      { text: "kernel: [    0.018901] usbcore: registered new interface driver libusual", delay: 4 },
      { text: "kernel: [    0.019012] usbcore: registered new interface driver usb-storage", delay: 4 },
      { text: "kernel: [    0.020123] Initializing USB Mass Storage driver", delay: 4 },
      { text: "kernel: [    0.021234] usbcore: registered new interface driver usb-storage", delay: 4 },
      { text: "kernel: [    0.022345] PnP: PS/2 Controller at 0x60,0x64", delay: 4 },
      { text: "kernel: [    0.023456] i8042: Detected controller", delay: 4 },
      { text: "kernel: [    0.024567] serio: i8042 KBD port", delay: 4 },
      { text: "kernel: [    0.025678] serio: i8042 AUX port", delay: 4 },
      { text: "kernel: [    0.026789] input: AT Raw Set 2 keyboard", delay: 4 },
      { text: "kernel: [    0.027890] mice: PS/2 mouse device common", delay: 4 },
      { text: "kernel: [    0.028901] md: linear personality registered", delay: 4 },
      { text: "kernel: [    0.029012] md: raid0 personality registered", delay: 4 },
      { text: "kernel: [    0.030123] md: raid1 personality registered", delay: 4 },
      { text: "kernel: [    0.031234] md: raid5 personality registered", delay: 4 },
      { text: "kernel: [    0.032345] md: raid6 personality registered", delay: 4 },
      { text: "kernel: [    0.033456] md: raid10 personality registered", delay: 4 },
      { text: "kernel: [    0.034567] block: cfq io scheduler registered", delay: 4 },
      { text: "kernel: [    0.035678] block: deadline io scheduler registered", delay: 4 },
      { text: "kernel: [    0.036789] block: noop io scheduler registered", delay: 4 },
      { text: "kernel: [    0.037890] loop: module loaded", delay: 4 },
      { text: "kernel: [    0.038901] tun: Universal TUN/TAP driver", delay: 4 },
      { text: "kernel: [    0.039012] PPP generic driver version 2.4.2", delay: 4 },
      { text: "kernel: [    0.040123] NET: Registered protocol family 2", delay: 4 },
      { text: "kernel: [    0.041234] NET: Registered protocol family 10", delay: 4 },
      { text: "kernel: [    0.042345] NET: Registered protocol family 17", delay: 4 },
      { text: "kernel: [    0.043456] NET: Registered protocol family 15", delay: 4 },
      { text: "kernel: [    0.044567] Ebtables v2.0 registered", delay: 4 },
      { text: "kernel: [    0.045678] ip_tables: (C) 2000-2006 Netfilter Core Team", delay: 4 },
      { text: "kernel: [    0.046789] arp_tables: (C) 2002 David S. Miller", delay: 4 },
      { text: "kernel: [    0.047890] TCP: cubic registered", delay: 4 },
      { text: "kernel: [    0.048901] NET: Registered protocol family 1", delay: 4 },
      { text: "kernel: [    0.049012] NET: Registered protocol family 31", delay: 4 },
      { text: "kernel: [    0.050123] RPC: Registered udp transport module", delay: 4 },
      { text: "kernel: [    0.051234] RPC: Registered tcp transport module", delay: 4 },
      { text: "kernel: [    0.052345] RPC: Registered tcp NFSv4.1 backchannel transport", delay: 4 },
      { text: "Starting kdm (KDE Display Manager)... [OK]", delay: 225 },
      { text: "Loading KDE libraries: libkdecore.so.3 [OK]", delay: 15 },
      { text: "Loading KDE libraries: libkdeui.so.3 [OK]", delay: 15 },
      { text: "Initializing artsd sound engine... [OK]", delay: 225 },
      { text: "KDE: Starting ksmserver (Session Manager)", delay: 75 },
      { text: "KDE: Starting kdesktop (Desktop Manager)", delay: 75 },
      { text: "KDE: Starting kicker (Panel)", delay: 75 },
      { text: "KDE: Starting klipper (Clipboard)", delay: 38 },
      { text: "KDE: Initializing Konqueror preloader...", delay: 150 },
      { text: "", delay: 75 },
      { text: "Debian GNU/Linux 2.2 'Potato' (Kernel 2.2.13)", delay: 225 },
      { text: "debian-station login: _", delay: 750 }
    ],

    /** Linux-Boot: Hacker-Glow (Matrix-Look), Scanlines – Ziel ~7 s */
    linuxBootHints: {
      targetDurationMs: 7000,
      /** Hintergrund fast schwarz, Neongrün, leichter Glow */
      monitor: {
        backgroundColor: "#050505",
        color: "#00FF41",
        fontFamily: "'VGA 437', 'Courier New', monospace",
        textShadow: "0 0 5px rgba(0, 255, 65, 0.7)"
      },
      prompt: "user@debian:~$",
      promptColor: "#00FF41",
      lineTypes: {
        standard: { color: "#00FF41" },
        ok: { color: "#55FF55" },
        warning: { color: "#FFFF55" }
      },
      body: {
        backgroundColor: "#050505",
        overflow: "hidden",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh"
      },
      monitor: {
        id: "monitor",
        width: "90vw",
        height: "80vh",
        backgroundColor: "#0a0a0a",
        border: "20px solid #333",
        borderRadius: "20px",
        boxShadow: "0 0 50px rgba(0, 255, 0, 0.1)",
        overflow: "hidden",
        position: "relative"
      },
      bootContainer: {
        id: "boot-container",
        padding: "20px",
        fontFamily: "'Courier New', monospace",
        fontSize: "14px",
        color: "#00ff41",
        textShadow: "0 0 5px rgba(0, 255, 0, 0.7)",
        lineHeight: "1.2",
        height: "100%",
        overflowY: "hidden"
      },
      scanlines: "::before auf #monitor: linear-gradient(rgba(18,16,16,0) 50%, rgba(0,0,0,0.25) 50%), linear-gradient(90deg, rgba(255,0,0,0.06), rgba(0,255,0,0.02), rgba(0,0,118,0.06)); background-size: 100% 4px, 3px 100%; z-index: 2",
      flicker: "keyframes: 0% opacity 0.97, 5% 0.95, 10% 0.9, 100% 1; animation auf #monitor: flicker 0.1s infinite",
      errorColor: "#ff4444"
    },

    /** 1_bootvorgang: Mac-spezifischer Boot (EFI, Darwin, APFS) – Mac-Nutzer erkennen sich wieder */
    macLines: [
      "*** Boot Args: -v",
      "Standard EFI Firmware v14.0.0.0.0 (release)",
      "Initializing Console... [DONE]",
      "[OK] Searching for Boot Volume...",
      "[OK] Found APFS Volume: Macintosh HD (UUID: 5E8C82B1-4A2D-4F1E-9C8A-F21B320491F0)",
      "[OK] Executing Boot Loader (boot.efi)...",
      "[OK] Loading Kernel Cache...",
      "[OK] Loading Kernel Extensions (KEXTS)...",
      "Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103",
      "[    0.000000] core crypto: initialized",
      "[    0.000000] mem_management: 16GB RAM detected (LPDDR4X)",
      "[    0.000010] pmap_bootstrap: memory range 0x0 - 0x400000000",
      "[    0.000124] AppleACPICPU: proc 0:1, 1:1, 2:1, 3:1, 4:1, 5:1, 6:1, 7:1",
      "[    0.001050] AppleARMPlatform: Power management initialized",
      "[    0.002450] IOAPIC: Version 0x11 Vectors 64:87",
      "[    0.005120] ACPI: System State [S0 S3 S4 S5]",
      "[    0.010450] PCI: Root Bridge [PCI0] initialized",
      "[    0.015234] PCI: Scanning for devices...",
      "[    0.020110] PCI: Found device [0x106b:0x1000] at 00:01.0",
      "[    0.045230] PCI: Found device [0x106b:0x1001] at 00:02.0",
      "[    0.104820] PCI: Internal bridge initialization complete",
      "[    0.115932] AppleEmbeddedPCI: Link up, Gen3 x4",
      "[    0.125430] IOKit: Service match: AppleEmbeddedUSBHost",
      "[    0.150492] AppleT8103: PMGR initialized",
      "[    0.187643] vm_page_bootstrap: 245760 free pages and 12288 wired pages",
      "[    0.210542] kext submap [0x12345678 - 0x87654321], footprint: 1876432",
      "[    0.224102] AppleSEPKeyStore: operation start",
      "[    0.245892] disk0: Apple NVMe Controller (v2.1) - 512GB",
      "[    0.246102] disk0s1: EFI (FAT32) [512MB]",
      "[    0.246453] disk0s2: APFS Container (0x7F) [476GB]",
      "[    0.280121] apfs: dev_block_size 4096, block_count 125000000",
      "[    0.295432] apfs_vfs_mount: Scanning container structures...",
      "[    0.310452] apfs_vfs_mount: Macintosh HD (Data) mounted successfully",
      "[    0.315992] AppleKeyStore: established session (0x1)",
      "[    0.334102] AppleCredentialManager: initialized",
      "[    0.354120] [KEXT] com.apple.driver.AppleACPIPlatform (1.0) loaded",
      "[    0.365432] [KEXT] com.apple.iokit.IOPCIFamily (2.9) loaded",
      "[    0.375210] [KEXT] com.apple.iokit.IOReportFamily (47) loaded",
      "[    0.382103] [KEXT] com.apple.iokit.IOStorageFamily (2.1) loaded",
      "[    0.395431] [KEXT] com.apple.driver.AppleMobileFileIntegrity (1.0.5) loaded",
      "[    0.410231] [KEXT] com.apple.driver.AppleEmbeddedOSSupportHost (1.0) loaded",
      "[    0.425430] [KEXT] com.apple.iokit.IONetworkingFamily (3.4) loaded",
      "[    0.440212] Ethernet [en0]: AppleBCM5701Ethernet - Link up at 1000 Mbps",
      "[    0.465432] Ethernet [en0]: MAC address 00:3e:e1:c4:b2:01",
      "[    0.501234] AirPort: Link up on en1 (802.11ax)",
      "[    0.515432] AirPort: BSSID 1c:b0:44:21:a2:ff",
      "[    0.530211] AppleFileSystemDriver: Version 23.0.1 (APFS)",
      "[    0.550121] Bluetooth: HCI_RESET_COMMAND sent...",
      "[    0.582103] Bluetooth: Controller detected (Apple Internal USB)",
      "[    0.595432] Bluetooth: VendorID: 0x05AC, ProductID: 0x821F",
      "[    0.612450] IOBluetoothFamily: Initializing Internal Controller... [OK]",
      "[    0.654321] IOGraphics: Initializing framebuffer...",
      "[    0.701234] USB: [Controller 0x1] Initializing XHCI Root Hub",
      "[    0.725431] USB: [Port 0x1] Device connected (0x05ac:0x0272)",
      "[    0.754322] USB: [Port 0x2] Device connected (0x05ac:0x0273)",
      "[    0.781230] USB: [Controller 0x1] Hub 0x1 initialized",
      "[    0.812450] USB: [Device 0x1] Apple Keyboard (Internal) connected",
      "[    0.814502] USB: [Device 0x2] Apple Trackpad (Internal) connected",
      "[    0.854321] IOKit: HID descriptor received from device 0x1",
      "[    0.910234] AppleSmartBattery: polling battery status...",
      "[    0.935432] AppleSmartBattery: Battery is charging (92%)",
      "[    1.102341] Graphics: Apple M-Series (Metal 3.0 support)",
      "[    1.154321] Graphics: CoreDisplay version 1.0.0",
      "[    1.205492] Graphics: Framebuffer initialized at 0x80000000",
      "[    1.254321] Graphics: Resolution 2560x1600 (32-bit color)",
      "[    1.310421] HID: Legacy shim 2 initialized",
      "[    1.354321] HID: Pointer events registered",
      "[    1.402341] Security: Checking integrity of Boot Policy...",
      "[    1.450121] Security: SIP is enabled (0x0)",
      "[    1.452932] Security: AMFI initialized (v2.0)",
      "[    1.485432] Security: AppleMobileFileIntegrity policy loaded",
      "[    1.501230] launchd: Starting system daemons...",
      "[    1.512302] launchd: [com.apple.syslogd] started (pid: 148)",
      "[    1.520412] launchd: [com.apple.WindowServer] started (pid: 142)",
      "[    1.525992] launchd: [com.apple.DirectoryService] started (pid: 145)",
      "[    1.535432] launchd: [com.apple.notifyd] started (pid: 149)",
      "[    1.545210] launchd: [com.apple.diskarbitrationd] started (pid: 150)",
      "[    1.550102] launchd: [com.apple.configd] started (pid: 152)",
      "[    1.555431] launchd: [com.apple.securityd] started (pid: 153)",
      "[    1.560231] launchd: [com.apple.mDNSResponder] started (pid: 155)",
      "[    1.570432] launchd: [com.apple.opendirectoryd] started (pid: 158)",
      "[    1.585210] launchd: [com.apple.fseventsd] started (pid: 160)",
      "[    1.595432] launchd: [com.apple.powerd] started (pid: 162)",
      "[    1.610231] launchd: [com.apple.coreduetd] started (pid: 165)",
      "[    1.625432] launchd: [com.apple.locationd] started (pid: 168)",
      "[    1.640210] launchd: [com.apple.cloudd] started (pid: 170)",
      "[    1.655431] launchd: [com.apple.apsd] started (pid: 172)",
      "[    1.670234] launchd: [com.apple.identityservicesd] started (pid: 175)",
      "[    1.685432] launchd: [com.apple.sharingd] started (pid: 178)",
      "[    1.701210] AppleBCMWLAN: Link event (Reason: 0)",
      "[    1.725432] AppleBCMWLAN: Channel scan complete",
      "[    1.754321] IOAudio: Initializing Core Audio drivers...",
      "[    1.782001] IOConsoleUsers: time(0) 0->0, Lin 0, LLK 1",
      "[    1.785021] IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0",
      "[    1.810432] Sandbox: loginwindow (pid 142) deny(1) file-read-data /private/var/db/diagnostics",
      "[    1.854321] hfs: mounted Recovery HD on device disk0s3",
      "[    1.902341] DirectoryService: Bound to local node (LDAP)",
      "[    1.954321] AppleCredentialManager: Authentication policy set",
      "[    2.001230] loginwindow: waiting for user activity...",
      "[    2.054321] loginwindow: load UI [Done]",
      "[    2.102341] loginwindow: user activity detected",
      "[    2.154321] AppleMesa: Graphics context established",
      "[    2.201234] WindowServer: Session initialized (0x0)",
      "[    2.210942] === System Boot Complete (Uptime: 2.21s) ===",
      "[    2.220101] login: Displaying Login Panel for user 'admin'"
    ],

    /** Mac-Boot: Ziel ~7 s – View nutzt defaultDelayMs pro Zeile (105 Zeilen × 67 ms ≈ 7 s) */
    macBootHints: {
      targetDurationMs: 7000,
      defaultDelayMs: 67,
      /** Monitor-Container: .mac-monitor */
      monitor: {
        backgroundColor: "#000000",
        color: "#F5F5F7",
        fontFamily: "\"SF Mono\", \"Menlo\", \"Monaco\", \"Courier New\", monospace",
        fontSize: "13px",
        letterSpacing: "-0.2px",
        padding: "30px",
        webkitFontSmoothing: "antialiased"
      },
      /** Zeilen-Typen für CSS-Klassen */
      prompt: "MacBook-Pro:~ user$",
      promptColor: "#FFFFFF",
      lineTypes: {
        timestamp: { color: "#A1A1A6", marginRight: "10px" },
        kernelInfo: { color: "#FFFFFF", fontWeight: "600" },
        systemTag: { color: "#A1A1A6" }
      },
      /** Quartz/Unix-Look: kein Glow, Anti-Aliasing – Schrift dünn/edel */
      webkitFontSmoothing: "antialiased",
      cssSnippet: ".mac-monitor{background:#000;color:#F5F5F7;font-family:'Monaco','Menlo','SF Mono',monospace;font-size:13px;letter-spacing:-0.2px;padding:30px;-webkit-font-smoothing:antialiased}.mac-timestamp{color:#A1A1A6;margin-right:10px}.mac-kernel-info{color:#FFF;font-weight:600}"
    },

    /** 1_bootvorgang: Windows 95 Boot (AMIBIOS, HIMEM, VXD) – ~7 s max */
    winBootSequence: [
      { text: "AMIBIOS (C)1992 American Megatrends Inc.,", delay: 35 },
      { text: "06/12/95-I430FX-2A59CF09C-00", delay: 18 },
      { text: "Processor: Intel Pentium(R) 133 MHz", delay: 18 },
      { text: "Memory Test : 32768 KB OK", delay: 430 },
      { text: "", delay: 35 },
      { text: "Award Plug and Play BIOS Extension v1.0A", delay: 35 },
      { text: "Initialize Plug and Play Cards...", delay: 145 },
      { text: "PNP Init Completed", delay: 35 },
      { text: "", delay: 35 },
      { text: "Detecting IDE Primary Master ... [ST31276A]", delay: 215 },
      { text: "Detecting IDE Primary Slave  ... [None]", delay: 70 },
      { text: "Detecting IDE Secondary Master... [CR-581-B]", delay: 180 },
      { text: "Detecting IDE Secondary Slave ... [None]", delay: 35 },
      { text: "", delay: 35 },
      { text: "Floppy drive A: 1.44M, 3.5 in.", delay: 110 },
      { text: "Floppy drive B: None", delay: 18 },
      { text: "Display Type: VGA/EGA", delay: 35 },
      { text: "Serial Port(s) : 3F8 2F8", delay: 18 },
      { text: "Parallel Port(s): 378", delay: 18 },
      { text: "", delay: 35 },
      { text: "Starting Windows 95...", delay: 360 },
      { text: "", delay: 35 },
      { text: "Microsoft(R) Windows 95", delay: 70 },
      { text: "   (C)Copyright Microsoft Corp 1981-1995.", delay: 70 },
      { text: "", delay: 35 },
      { text: "C:\\>SET SOUND=C:\\SB16", delay: 18 },
      { text: "C:\\>SET BLASTER=A220 I5 D1 H5 P330 T6", delay: 18 },
      { text: "C:\\>SET PATH=C:\\WINDOWS;C:\\WINDOWS\\COMMAND;C:\\DOS", delay: 18 },
      { text: "C:\\>C:\\SB16\\DIAGNOSE /S", delay: 145 },
      { text: "[OK] Sound Blaster 16 Configuration Successful", delay: 35 },
      { text: "C:\\>C:\\SB16\\MIXERSET /P /Q", delay: 35 },
      { text: "", delay: 35 },
      { text: "C:\\>DEVICE=C:\\WINDOWS\\HIMEM.SYS", delay: 35 },
      { text: "HIMEM: DOS Memory Manager v3.95", delay: 18 },
      { text: "Copyright (c) 1985, 1995 Microsoft Corp.", delay: 18 },
      { text: "HIMEM is testing extended memory...", delay: 540 },
      { text: "done.", delay: 35 },
      { text: "", delay: 35 },
      { text: "C:\\>DEVICE=C:\\WINDOWS\\EMM386.EXE NOEMS", delay: 35 },
      { text: "EMM386 Version 4.49", delay: 18 },
      { text: "Copyright (c) 1988, 1995 Microsoft Corp.", delay: 18 },
      { text: "Expanded memory services unavailable.", delay: 35 },
      { text: "", delay: 35 },
      { text: "C:\\>DEVICEHIGH=C:\\WINDOWS\\COMMAND\\ANSI.SYS", delay: 18 },
      { text: "C:\\>DEVICEHIGH=C:\\WINDOWS\\IFSHLP.SYS", delay: 18 },
      { text: "", delay: 35 },
      { text: "C:\\>C:\\WINDOWS\\smartdrv.exe /X", delay: 70 },
      { text: "C:\\>C:\\WINDOWS\\COMMAND\\MSCDEX.EXE /D:mscd001 /L:D", delay: 215 },
      { text: "MSCDEX Version 2.25", delay: 18 },
      { text: "Copyright (C) Microsoft Corp. 1986-1995. All rights reserved.", delay: 18 },
      { text: "       Drive D: = Driver MSCD001 unit 0", delay: 35 },
      { text: "", delay: 35 },
      { text: "Windows is verifying file system structures...", delay: 290 },
      { text: "Checking C: [FAT16]", delay: 70 },
      { text: "Clusters: 65,536", delay: 70 },
      { text: "Checking Directory Tree...", delay: 110 },
      { text: "Checking Free Space...", delay: 110 },
      { text: "Windows has finished checking the drive.", delay: 70 },
      { text: "", delay: 35 },
      { text: "Loading System Drivers (VMM32)...", delay: 180 },
      { text: "[VXD] Loading VMM32.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading CONFIGMG.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading NTKERN.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VPICD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VTD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VREBOOT.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VDMAD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VSD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading V86MMGR.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading PAGESWAP.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading DOSMGR.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VMCPD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VPOWERD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VWIN32.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VCOMM.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading COMBUFF.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VCD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VPD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VFLATD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VDD.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VSHARE.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading IFSMGR.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading IOS.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VCACHE.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VFAT.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VCOND.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VNPDRV.VXD... [OK]", delay: 11 },
      { text: "[VXD] Loading VNETBIOS.VXD... [OK]", delay: 11 },
      { text: "", delay: 35 },
      { text: "Initializing Network Stack...", delay: 145 },
      { text: "[NET] Loading NDIS.VXD... [OK]", delay: 35 },
      { text: "[NET] Binding TCP/IP to Ethernet Adapter...", delay: 180 },
      { text: "[NET] IP Address: 192.168.1.15", delay: 35 },
      { text: "[NET] Workgroup: WORKGROUP", delay: 35 },
      { text: "", delay: 35 },
      { text: "Starting GUI Components...", delay: 215 },
      { text: "[SYS] Initializing GDI.EXE...", delay: 70 },
      { text: "[SYS] Initializing USER.EXE...", delay: 70 },
      { text: "[SYS] Initializing KERNEL32.DLL...", delay: 70 },
      { text: "[SYS] Loading Fonts... [OK]", delay: 110 },
      { text: "[SYS] Loading Desktop Wallpaper... [OK]", delay: 110 },
      { text: "", delay: 35 },
      { text: "C:\\WINDOWS\\WIN.COM", delay: 180 },
      { text: "Executing AUTOEXEC.BAT...", delay: 70 },
      { text: "Starting Explorer Shell...", delay: 360 },
      { text: "", delay: 35 },
      { text: "Welcome to Windows 95.", delay: 180 }
    ],

    /** Win95-Layout-Hinweise (Retro-Style für View) – Delays in winBootSequence bereits auf ~7 s skaliert */
    winBootHints: {
      /** Monitor-Container: .win-monitor */
      /** Office-Look: trocken, funktional, keine Glow – Schrift hart/pixelig */
      monitor: {
        backgroundColor: "#000000",
        color: "#C0C0C0",
        fontFamily: "'Fixedsys', 'Lucida Console', monospace",
        fontSize: "14px",
        textShadow: "none",
        padding: "20px"
      },
      prompt: "C:\\WINDOWS>",
      promptColor: "#C0C0C0",
      lineTypes: {
        bios: { color: "#FFFFFF", fontWeight: "bold" },
        cmd: { color: "#C0C0C0" },
        ok: { color: "#00FF00" }
      },
      scanlines: true,
      cssSnippet: ".win-monitor{background:#000;color:#C0C0C0;font-family:'Fixedsys','Lucida Console',monospace;font-size:14px;padding:20px}.win-line-bios{color:#FFF;font-weight:bold}.win-line-cmd{color:#C0C0C0}.win-line-ok{color:#00FF00}"
    },

    /** 1_bootvorgang: Ende für Mac/Win/Linux: systemAnalyzed = "System wird analysiert – {os} erkannt", done = "Bootvorgang abgeschlossen." */
    macWinLinux: {
      systemAnalyzed: "System wird analysiert – {os} erkannt",
      done: "Bootvorgang abgeschlossen."
    },

    /** 1_bootvorgang: Abgebrochener Boot für iPhone (Redirect passiert vorher – iOS wird hier nie erreicht; für Vollständigkeit) */
    iphoneAborted: [
      "iPhone erkannt",
      "Systemfehler: Bootsektoren nicht gefunden",
      "DFU wird gestartet"
    ],

    /** 2.5_iphone: Abgebrochener Boot – Kurzversion (Easter Egg + Speicherfehler + DFU) */
    iphoneShort: [
      { text: "[    0.000000] Linux version 6.1.0-25-generic", cls: "" },
      { text: "[    0.000001] Command line: BOOT_IMAGE=/vmlinuz root=UUID=xxx ro quiet splash", cls: "" },
      { text: "[    0.001234] e820: BIOS-provided physical RAM map", cls: "" },
      { text: "[    0.012345] Zone ranges:", cls: "" },
      { text: "[    0.023456] Initramfs unpacking: Done", cls: "" },
      { text: "[    0.045678] PCI: CLS 64 bytes, default 64", cls: "" },
      { text: "[    0.123456] iommu: Default domain type: Translated", cls: "" },
      { text: "[    0.234567] systemd[1]: systemd 252.5 running in system mode", cls: "" },
      { text: "[    0.267890] systemd[1]: Set hostname to <host>", cls: "" },
      { text: "[    0.389012] systemd[1]: Reached target System Initialization", cls: "" },
      { text: "23 Easter Eggs gefunden.", cls: "" },
      { text: "Speicherfehler", cls: "error" },
      { text: "Starte DFU-Modus...", cls: "" }
    ],

    /** 2.5_iphone: Systemfehler-Overlay (Finder-Desktop) */
    iphoneSystemfehler: [
      { text: "DFU konnte nicht gestartet werden", isError: false },
      { text: "Systemfehler", isError: true },
      { text: "DFU erneut starten", isError: false }
    ],

    /** 2.5_iphone: DFU-Screen */
    iphoneDfu: {
      title: "DFU gestartet",
      sub: "Wiederherstellung beginnen."
    },

    /** Nach dem Boot: Eingabeaufforderung / Terminal – kaffeemaschine-Installation einleiten */
    terminalScripts: {
      /** Windows 95/98: Grau, blockig, deutsche Systemsprache, MS-DOS */
      win: [
        { text: "C:\\WINDOWS> cls", delay: 1000 },
        { text: "Installation von kaffeemaschine.exe beginnt...", delay: 500 }
      ],
      /** Linux Retro (Slackware/Debian): Hacker-Grün, Englisch, sudo */
      linux: [
        { text: "Access granted to kernel-layer.", delay: 300 },
        { text: "user@debian:~$ clear", delay: 1000 },
        { text: "Reading package lists... Done. Installing coffee-mod...", delay: 200 }
      ],
      /** macOS Classic: Kaltweiß, Unix-Befehle, echo/sudo */
      mac: [
        { text: "[KEXT] com.apple.iokit.IOStorageFamily loaded", delay: 50 },
        { text: "Waiting for Root Device... Got boot device", delay: 300 },
        { text: "Graphics Start: AppleDisplay initialized", delay: 100 },
        { text: "MacBook-Pro:~ user$ echo \"Booting into Deep Work...\"", delay: 800 },
        { text: "==> Deep Work Mode activated via AppleScript", delay: 400 },
        { text: "MacBook-Pro:~ user$ clear", delay: 1000 },
        { text: "==> Extracting kaffeemaschine.ipa (v2.0.2026)...", delay: 300 }
      ]
    },

    /** Farb-DNA der drei Terminals – CSS-Klassen .term-win / .term-linux / .term-mac zum Umschalten */
    terminalStyleDna: {
      win: {
        className: "term-win",
        background: "#000000",
        color: "#C0C0C0",
        highlight: "#FFFFFF",
        prompt: "C:\\WINDOWS>",
        promptColor: "#C0C0C0",
        fontFamily: "'Fixedsys', 'Lucida Console', monospace",
        textShadow: "none",
        vibe: "Office-Look: trocken, funktional, hart/pixelig"
      },
      linux: {
        className: "term-linux",
        background: "#050505",
        color: "#00FF41",
        highlight: "#55FF55",
        warning: "#FFFF55",
        prompt: "user@debian:~$",
        promptColor: "#00FF41",
        fontFamily: "'VGA 437', 'Courier New', monospace",
        textShadow: "0 0 8px rgba(0, 255, 65, 0.7)",
        vibe: "Hacker-Glow, Matrix-Look"
      },
      mac: {
        className: "term-mac",
        background: "#000000",
        color: "#F5F5F7",
        systemTag: "#A1A1A6",
        prompt: "MacBook-Pro:~ user$",
        promptColor: "#FFFFFF",
        fontFamily: "'Monaco', 'Menlo', 'SF Mono', monospace",
        letterSpacing: "-0.2px",
        webkitFontSmoothing: "antialiased",
        textShadow: "none",
        vibe: "Quartz/Unix-Look, dünn/edel"
      }
    },

    /** 2_mac / 2.1_win / 2.3_linux: Boot-Screen (Progress-Bar) */
    bootScreen: {
      initialStatus: "Initialisierung...",
      initialOs: "Betriebssystem wird erkannt...",
      osLabels: {
        win: "Windows erkannt – cmd.exe wird vorbereitet",
        mac: "macOS erkannt – Terminal.app wird gestartet",
        linux: "Linux erkannt – bash wird geladen",
        android: "Android erkannt – Shell wird geöffnet",
        ios: "iOS erkannt – Terminal wird simuliert"
      },
      steps: [
        { pct: 15, status: "Systemressourcen prüfen..." },
        { pct: 32, statusTerminal: "Terminal-Emulator laden...", statusShell: "Shell-Emulator laden..." },
        { pct: 51, status: "Umgebungsvariablen setzen..." },
        { pct: 68, status: "Shell initialisieren..." },
        { pct: 84, status: "Verbindung herstellen..." },
        { pct: 100, status: "Bereit." }
      ],
      readyTerminal: "Terminal bereit.",
      readyShell: "Shell bereit."
    }
  };
})();
